# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

# robots = ""
languageCode = "fr"
languageName = "French"
displayName = ":fr:"
isoCode = "fr"
weight = 1
rtl = false

title = "fchevalier.net"
description = "Blog et portofolio de Fabien, proposant des articles et projets ayant pour sujet les pratiques DevOps et le cloud"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

mainSections = ["blog", "projets"]

[author]
name = "Fabien CHEVALIER"
image = "img/author.png"
headline = ":cloud: DevOps engineer / :musical_note: Music Artist"
bio = "DevOps :cloud: @claranet-france - :laptop: Computer geek and open-source lover"
links = [
  { email = "mailto:contact@fchevalier.net" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/fabienchevalier" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  { linkedin = "https://linkedin.com/in/fabche" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  { soundcloud = "https://soundcloud.com/user-351918779" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
]

[header]
layout = "classic"      # valid options: basic, hamburger, hybrid, custom
logo = "img/logo.png"
showTitle = true

[footer]
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "profile" # valid options: page, profile, custom
showRecent = true
recentLimit = 5


[article]
showDate = true
showDateUpdated = false
showAuthor = true
showBreadcrumbs = false
showDraftLabel = true
showEdit = false
editURL = "https://github.com/fabienchevalier/fabienchevalier.github.io"
editAppendPath = true
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = false
showTaxonomies = false
showWordCount = false
showComments = false
sharingLinks = [
  "facebook",
  "twitter",
  "mastodon",
  "pinterest",
  "reddit",
  "linkedin",
  "email",
]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showTaxonomies = false
groupByYear = true
paginationWidth = 1

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
